### ISSUE TITLE
Library should not contain(almost) any unwrap/expect calls

### ISSUE THREAD

**Issue by qarmin** [styrowolf/pdf2image#1]

**Comment by qarmin** [comment]
https://github.com/styrowolf/pdf2image/blob/b567ba75893d73e8d45db603be2a784af5574df2/src/pdf.rs#L156

https://github.com/styrowolf/pdf2image/blob/b567ba75893d73e8d45db603be2a784af5574df2/src/pdf.rs#L140

**Comment by styrowolf** [comment]
Fixed with commit [a163774](https://github.com/styrowolf/pdf2image/commit/a1637744cee060fabd28fdac2c5891291c254a1e). I removed unnecessary unwraps and added comments to safe ones. Thank you!
